export default {
  board: {},
  highlightedGame: null,
  boards: [],
  games: {},
  dragging: false,
  scrolled: false,
  game: null,
  cachedGames: {},
  notes: {},
  notification: false,
  platforms: [],
  profile: {},
  profiles: [],
  progresses: {},
  publicBoards: [],
  releases: [],
  sessionExpired: false,
  settings: {},
  tags: [],
  twitchToken: null,
  user: null,
  wallpapers: [],
};
