export default {
  user: null,
  tags: {},
  notes: {},
  profile: {},
  profiles: [],
  releases: [],
  progresses: {},
  dragging: false,
  settings: {},
  results: [], // TODO: remove from store
  games: {},
  boards: [],
  publicBoards: [],
  board: {},
  boardGames: [],
  activeGame: {
    gameId: null,
    list: null,
  },
  wallpapers: [],
  platform: null,
  sessionExpired: false,
  twitchToken: null,
  notification: false,
};
