export default [
    {
        name: 'Xbox One',
        code: 'xbox-one',
        id: 49,
        generation: 8,
    },
    {
        name: 'Nintendo Switch',
        code: 'nintendo-switch',
        hex: '#e60012',
        id: 130,
        generation: 8,
    },
    {
        name: 'NES',
        code: 'nes',
        hex: '#FFFFFF',
        id: 18,
        generation: 3,
    },
    {
        name: 'Wii',
        code: 'wii',
        hex: '#FFFFFF',
        id: 5,
        generation: 7,
    },
    {
        name: 'Nintendo 64',
        code: 'nintendo-64',
        id: 4,
        generation: 5,
    },
    {
        name: 'Playstation',
        code: 'ps',
        hex: '#fff',
        id: 7,
        generation: 5,
    },
    {
        name: 'Playstation 2',
        code: 'ps2',
        hex: '#fff',
        id: 8,
        generation: 6,
    },
    {
        name: 'Playstation 3',
        code: 'ps3',
        hex: '#fff',
        id: 9,
        generation: 7,
    },
    {
        name: 'PlayStation 4',
        code: 'ps4',
        hex: '#2E6DB4',
        id: 48,
        generation: 8,
    },
    {
        name: 'PC - Windows',
        code: 'win',
        id: 6,
        generation: '0',
    },
    {
        name: 'Super Nintendo',
        code: 'snes',
        id: 19,
        generation: 4,
    },
    {
        name: 'Sega Mega Drive / Genesis',
        code: 'sega-genesis',
        id: 29,
        generation: 4,
    },
    {
        name: 'Xbox',
        code: 'xbox',
        id: 11,
        generation: 6,
    },
    {
        name: 'Xbox 360',
        code: 'xbox-360',
        id: 12,
        generation: 7,
    },
    {
        name: 'PC Dos',
        code: 'msdos',
        id: 13,
        generation: '0',
    },
    {
        name: 'Mac',
        code: 'mac',
        id: 14,
        generation: '0',
    },
    {
        name: 'Commodore C64/128',
        code: 'commodore-64',
        id: 15,
        generation: '0',
    },
    {
        name: 'Amiga',
        code: 'amiga',
        navHex: '#fff',
        id: 16,
        generation: '0',
    },
    {
        name: 'Nintendo DS',
        code: 'nintendo-ds',
        id: 20,
        generation: 7,
        // Combine
        // id: 159,
    },
    {
        name: 'Nintendo GameCube',
        code: 'nintendo-gamecube',
        id: 21,
        generation: 6,
    },
    {
        name: 'Game Boy Color',
        code: 'gameboy-color',
        id: 22,
        generation: 5,
    },
    {
        name: 'Dreamcast',
        code: 'dreamcast',
        id: 23,
        generation: 6,
    },
    {
        name: 'Game Boy Advance',
        code: 'gameboy-advance',
        id: 24,
        generation: 6,
    },
    {
        name: 'Sega 32X',
        code: 'sega-32x',
        id: 30,
        generation: 4,
    },
    {
        name: 'Sega Saturn',
        code: 'sega-saturn',
        id: 32,
        generation: 5,
    },
    {
        name: 'Game Boy',
        code: 'gameboy',
        id: 33,
        generation: 4,
    },
    {
        name: 'Sega Game Gear',
        code: 'game-gear',
        id: 35,
        generation: 4,
    },
    {
        name: 'Nintendo 3DS',
        code: 'n3ds',
        id: 37,
        generation: 8,
    },
    {
        name: 'PSP',
        code: 'psp',
        id: 38,
        generation: 7,
    },
    {
        name: 'Wii U',
        code: 'wii-u',
        id: 41,
        generation: 8,
    },
    {
        name: 'PlayStation Vita',
        code: 'playstation-vita',
        id: 46,
        generation: 8,
    },
    {
        name: '3DO Interactive Multiplayer',
        code: '3do',
        navHex: '#000',
        id: 50,
        generation: 5,
    },
    {
        name: 'Atari 8-bit',
        code: 'atari-800',
        id: 65,
        generation: '0',
    },
    {
        name: 'Atari 2600',
        code: 'atari-2600',
        id: 59,
        generation: 2,
    },
    {
        name: 'Atari 7800',
        code: 'atari-7800',
        id: 60,
        generation: 3,
    },
    {
        name: 'Atari Lynx',
        code: 'atari-lynx',
        id: 61,
        generation: 4,
    },
    {
        name: 'Atari Jaguar',
        code: 'atari-jaguar',
        id: 62,
        generation: 5,
    },
    {
        name: 'Atari ST',
        code: 'atari-st',
        id: 63,
        generation: '0',
    },
    {
        name: 'Sega Master System',
        code: 'sega-master-system',
        id: 64,
        generation: 3,
    },
    {
        name: 'Atari 5200',
        code: 'atari-5200',
        id: 66,
        generation: 2,
    },
    {
        name: 'Intellivision',
        code: 'intellivision',
        id: 67,
        generation: 2,
    },
    {
        name: 'ColecoVision',
        code: 'colecovision',
        id: 68,
        generation: 2,
    },
    {
        name: 'Vectrex',
        code: 'vectrex',
        id: 70,
        generation: 2,
    },
    {
        name: 'Commodore VIC-20',
        code: 'vic-20',
        id: 71,
        generation: '0',
    },
    {
        name: 'Apple II',
        code: 'apple-2',
        hex: '#fff',
        id: 75,
        generation: '0',
    },
    {
        name: 'Sega CD',
        code: 'sega-cd',
        hex: '#000',
        id: 78,
        generation: 4,
    },
    {
        name: 'Neo Geo MVS',
        code: 'neo-geo',
        id: 79,
        generation: '0',
        // TODO: combine
        // id: 80,
    },
    {
        name: 'TurboGrafx-16 / PC Engine',
        code: 'pc-engine',
        id: 86,
        generation: 4,
        // name: 'PC Engine SuperGrafx (combine with pc engine)',
        // id: 128,
    },
    {
        name: 'Nintendo Virtual Boy',
        code: 'virtual-boy',
        id: 87,
        generation: 5,
    },
    {
        name: 'Odyssey',
        code: 'odyssey',
        id: 88,
        generation: 1,
    },
    // {
    //     name: 'Commodore PET',
    //     code: 'commodore-pet',
    //     id: 89,
    // },
    {
        name: 'Commodore 16',
        code: 'commodore',
        id: 93,
        generation: '0',
    },
    // {
    //     name: 'Philips CD-i',
    //     code: 'philips-cd-i',
    //     id: 117,
    // },
    {
        name: 'Neo Geo Pocket',
        code: 'neo-geo-pocket',
        id: 119,
        generation: 5,
    },
    // {
    //     name: 'Neo Geo Pocket Color',
    //     code: 'neo-geo-pocket-color',
    //     id: 120,
    // },
    {
        name: 'WonderSwan Color',
        code: 'wonderswan-color',
        id: 123,
        generation: 5,
    },
    {
        name: 'Neo Geo CD',
        code: 'neo-geo-cd',
        id: 136,
        generation: 4,
    },
    {
        name: 'Turbografx-16/PC Engine CD',
        code: 'turbografx-16',
        hex: '#000',
        id: 150,
        generation: 4,
    },
];
