export default [
    {
        name: 'Xbox One',
        code: 'xbox-one',
        hex: '#ffffff',
        textHex: '#107c10',
        id: 49,
        generation: 8,
    },
    {
        name: 'Nintendo Switch',
        code: 'nintendo-switch',
        hex: '#e60012',
        id: 130,
        generation: 8,
    },
    {
        name: 'NES',
        code: 'nes',
        hex: '#FFFFFF',
        textHex: '#DD002A',
        id: 18,
        generation: 3,
    },
    {
        name: 'Wii',
        code: 'wii',
        hex: '#FFFFFF',
        textHex: '#5ACDEA',
        id: 5,
        generation: 7,
    },
    {
        name: 'Nintendo 64',
        code: 'n64',
        hex: '#FFFFFF',
        textHex: '#D20014',
        id: 4,
        generation: 5,
    },
    {
        name: 'Playstation',
        code: 'ps',
        hex: '#fff',
        textHex: '#000',
        id: 7,
        generation: 5,
    },
    {
        name: 'Playstation 2',
        code: 'ps2',
        hex: '#fff',
        textHex: '#000',
        id: 8,
        generation: 6,
    },
    {
        name: 'Playstation 3',
        code: 'ps3',
        hex: '#fff',
        textHex: '#000',
        id: 9,
        generation: 7,
    },
    {
        name: 'PlayStation 4',
        code: 'ps4',
        hex: '#2E6DB4',
        id: 48,
        generation: 8,
    },
    {
        name: 'PC - Windows',
        code: 'win',
        hex: '#ffffff',
        textHex: '#0076d6',
        id: 6,
        generation: 8,
    },
    {
        name: 'Super Nintendo',
        code: 'snes',
        hex: '#ffffff',
        textHex: '#4f43ae',
        id: 19,
        generation: 4,
    },
    {
        name: 'Sega Mega Drive / Genesis',
        code: 'smd',
        hex: '#ffffff',
        textHex: '#000000',
        id: 29,
        generation: 4,
    },
];
