// Platforms reference:
// https://gist.github.com/romancm/3e58f307b8c475cace6a28eae8aee2b5
export default [
  {
    name: 'Nintendo Switch',
    code: 'nintendo-switch',
    hex: '#ce181e',
    releaseYear: 2017,
    id: 130,
    type: 'home',
  },
  {
    name: 'PlayStation 4',
    code: 'ps4',
    hex: '#2e6db4',
    releaseYear: 2013,
    type: 'home',
    id: 48,
  },
  {
    name: 'Xbox One',
    code: 'xbox-one',
    id: 49,
    releaseYear: 2013,
    type: 'home',
    hex: '#177d3e',
  },
  {
    name: 'PlayStation Vita',
    code: 'playstation-vita',
    id: 46,
    releaseYear: 2012,
    type: 'handheld',
  },
  {
    name: 'Steam',
    code: 'steam',
    id: 92,
    releaseYear: 2003,
    type: 'computer',
    hex: '#171a21',
  },
  {
    name: 'NES',
    code: 'nes',
    hex: '#ffffff',
    releaseYear: 1983,
    type: 'home',
    id: 18,
  },
  {
    name: 'Wii',
    code: 'wii',
    hex: '#ffffff',
    releaseYear: 2006,
    type: 'home',
    id: 5,
  },
  {
    name: 'Nintendo 64',
    code: 'nintendo-64',
    type: 'home',
    releaseYear: 1996,
    id: 4,
  },
  {
    name: 'Playstation',
    code: 'ps',
    hex: '#fff',
    type: 'home',
    releaseYear: 1994,
    id: 7,
  },
  {
    name: 'Playstation 2',
    code: 'ps2',
    type: 'home',
    hex: '#fff',
    releaseYear: 2000,
    id: 8,
  },
  {
    name: 'Playstation 3',
    code: 'ps3',
    type: 'home',
    hex: '#fff',
    releaseYear: 2006,
    id: 9,
  },
  {
    name: 'PC - Windows',
    code: 'win',
    type: 'computer',
    releaseYear: 1985,
    id: 6,
  },
  {
    name: 'Super Nintendo',
    code: 'snes',
    type: 'home',
    releaseYear: 1990,
    id: 19,
  },
  {
    name: 'Sega Mega Drive / Genesis',
    code: 'sega-genesis',
    releaseYear: 1988,
    type: 'home',
    id: 29,
  },
  {
    name: 'Xbox',
    code: 'xbox',
    releaseYear: 2001,
    type: 'home',
    id: 11,
  },
  {
    name: 'Xbox 360',
    code: 'xbox-360',
    type: 'home',
    releaseYear: 2005,
    id: 12,
  },
  {
    name: 'MS-DOS',
    code: 'msdos',
    type: 'computer',
    releaseYear: 1981,
    id: 13,
  },
  {
    name: 'Mac',
    code: 'mac',
    type: 'computer',
    releaseYear: 2001,
    id: 14,
  },
  {
    name: 'Commodore C64/128',
    code: 'commodore-64',
    id: 15,
    type: 'computer',
    releaseYear: 1982,
    hex: '#6f685f',
  },
  {
    name: 'Amiga',
    code: 'amiga',
    type: 'computer',
    releaseYear: 1985,
    id: 16,
  },
  {
    name: 'Nintendo DS',
    code: 'nintendo-ds',
    id: '20,159',
    releaseYear: 2004,
    type: 'handheld',
  },
  {
    name: 'Nintendo GameCube',
    code: 'nintendo-gamecube',
    releaseYear: 2001,
    type: 'home',
    id: 21,
  },
  {
    name: 'Game Boy Color',
    code: 'gameboy-color',
    releaseYear: 1998,
    type: 'handheld',
    id: 22,
  },
  {
    name: 'Dreamcast',
    code: 'dreamcast',
    type: 'home',
    releaseYear: 1999,
    id: 23,
  },
  {
    name: 'Game Boy Advance',
    code: 'gameboy-advance',
    id: 24,
    type: 'handheld',
    releaseYear: 2001,
    hex: '#1F00CC',
  },
  {
    name: 'Sega 32X',
    code: 'sega-32x',
    type: 'home',
    releaseYear: 1994,
    id: 30,
  },
  {
    name: 'Sega Saturn',
    code: 'sega-saturn',
    type: 'home',
    releaseYear: 1995,
    id: 32,
  },
  {
    name: 'Game Boy',
    code: 'gameboy',
    type: 'handheld',
    releaseYear: 1989,
    id: 33,
  },
  {
    name: 'Sega Game Gear',
    code: 'game-gear',
    type: 'handheld',
    releaseYear: 1991,
    id: 35,
  },
  {
    name: 'Nintendo 3DS',
    code: 'n3ds',
    type: 'handheld',
    releaseYear: 2011,
    id: '37,137',
  },
  {
    name: 'PSP',
    code: 'psp',
    type: 'handheld',
    releaseYear: 2005,
    id: 38,
  },
  {
    name: 'Wii U',
    code: 'wii-u',
    id: 41,
    type: 'home',
    releaseYear: 2012,
  },
  {
    name: '3DO Interactive Multiplayer',
    code: '3do',
    type: 'home',
    releaseYear: 1993,
    id: 50,
  },
  {
    name: 'Atari 8-bit',
    code: 'atari-800',
    type: 'computer',
    releaseYear: 1979,
    id: 65,
  },
  {
    name: 'Atari 2600',
    code: 'atari-2600',
    type: 'home',
    id: 59,
    releaseYear: 1977,
  },
  {
    name: 'Atari 7800',
    code: 'atari-7800',
    type: 'home',
    releaseYear: 1986,
    id: 60,
  },
  {
    name: 'Neo Geo CD',
    code: 'neo-geo-cd',
    releaseYear: 1994,
    type: 'home',
    id: 136,
  },
  {
    name: 'Atari Lynx',
    code: 'atari-lynx',
    type: 'handheld',
    id: 61,
    releaseYear: 1989,
    hex: '#000',
  },
  {
    name: 'Atari Jaguar',
    code: 'atari-jaguar',
    type: 'home',
    id: 62,
    releaseYear: 1993,
    hex: '#231f20',
  },
  {
    name: 'Atari ST',
    code: 'atari-st',
    type: 'computer',
    releaseYear: 1985,
    id: 63,
  },
  {
    name: 'Sega Master System',
    code: 'sega-master-system',
    type: 'home',
    releaseYear: 1986,
    id: 64,
  },
  {
    name: 'Atari 5200',
    code: 'atari-5200',
    type: 'home',
    releaseYear: 1982,
    id: 66,
  },
  {
    name: 'Intellivision',
    code: 'intellivision',
    type: 'home',
    releaseYear: 1979,
    id: 67,
  },
  {
    name: 'ColecoVision',
    code: 'colecovision',
    id: 68,
    type: 'home',
    releaseYear: 1982,
    hex: '#000',
  },
  {
    name: 'Vectrex',
    code: 'vectrex',
    type: 'home',
    releaseYear: 1982,
    id: 70,
  },
  {
    name: 'Commodore VIC-20',
    code: 'vic-20',
    type: 'computer',
    releaseYear: 1980,
    id: 71,
  },
  {
    name: 'Apple II',
    code: 'apple-2',
    releaseYear: 1977,
    type: 'computer',
    hex: '#fff',
    id: 75,
  },
  {
    name: 'Sega CD',
    code: 'sega-cd',
    releaseYear: 1992,
    type: 'home',
    hex: '#000',
    id: 78,
  },
  {
    name: 'Neo Geo MVS',
    code: 'neo-geo',
    type: 'home',
    id: '79,80',
    releaseYear: 1990,
  },
  {
    name: 'TurboGrafx-16 / PC Engine',
    code: 'pc-engine',
    type: 'home',
    hex: '#000',
    id: '86,128,150',
    releaseYear: 1987,
  },
  {
    name: 'Nintendo Virtual Boy',
    code: 'virtual-boy',
    releaseYear: 1995,
    type: 'home',
    id: 87,
  },
  {
    name: 'Magnavox Odyssey',
    code: 'odyssey',
    type: 'home',
    releaseYear: 1972,
    id: 88,
  },
  // {
  //     name: 'Commodore PET',
  //     code: 'commodore-pet',
  //     id: 89,
  // },
  {
    name: 'Commodore 16',
    code: 'commodore',
    type: 'computer',
    releaseYear: 1984,
    id: 93,
  },
  // {
  //     name: 'Philips CD-i',
  //     code: 'philips-cd-i',
  //     id: 117,
  // },
  {
    name: 'Neo Geo Pocket',
    code: 'neo-geo-pocket',
    type: 'handheld',
    releaseYear: 1998,
    id: '119,120',
  },
  {
    name: 'WonderSwan Color',
    code: 'wonderswan-color',
    type: 'handheld',
    releaseYear: 2000,
    id: 123,
  },
];
