// Static version of https://bootswatch.com/api/4.json

export default [
  {
    name: 'Cerulean',
    description: 'A calm blue sky',
    thumbnail: 'https://bootswatch.com/cerulean/thumbnail.png',
    preview: 'https://bootswatch.com/cerulean/',
    css: 'https://bootswatch.com/4/cerulean/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/cerulean/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/cerulean/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/cerulean/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/cerulean/_variables.scss',
    dark: false,
  },
  {
    name: 'Cosmo',
    description: 'An ode to Metro',
    thumbnail: 'https://bootswatch.com/cosmo/thumbnail.png',
    preview: 'https://bootswatch.com/cosmo/',
    css: 'https://bootswatch.com/4/cosmo/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/cosmo/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/cosmo/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/cosmo/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/cosmo/_variables.scss',
    dark: false,
  },
  {
    name: 'Cyborg',
    description: 'Jet black and electric blue',
    thumbnail: 'https://bootswatch.com/cyborg/thumbnail.png',
    preview: 'https://bootswatch.com/cyborg/',
    css: 'https://bootswatch.com/4/cyborg/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/cyborg/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/cyborg/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/cyborg/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/cyborg/_variables.scss',
    dark: true,
  },
  {
    name: 'Darkly',
    description: 'Flatly in night mode',
    thumbnail: 'https://bootswatch.com/darkly/thumbnail.png',
    preview: 'https://bootswatch.com/darkly/',
    css: 'https://bootswatch.com/4/darkly/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/darkly/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/darkly/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/darkly/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/darkly/_variables.scss',
    dark: true,
  },
  {
    name: 'Flatly',
    description: 'Flat and modern',
    thumbnail: 'https://bootswatch.com/flatly/thumbnail.png',
    preview: 'https://bootswatch.com/flatly/',
    css: 'https://bootswatch.com/4/flatly/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/flatly/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/flatly/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/flatly/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/flatly/_variables.scss',
    dark: false,
  },
  {
    name: 'Journal',
    description: 'Crisp like a new sheet of paper',
    thumbnail: 'https://bootswatch.com/journal/thumbnail.png',
    preview: 'https://bootswatch.com/journal/',
    css: 'https://bootswatch.com/4/journal/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/journal/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/journal/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/journal/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/journal/_variables.scss',
    dark: false,
  },
  {
    name: 'Litera',
    description: 'The medium is the message',
    thumbnail: 'https://bootswatch.com/litera/thumbnail.png',
    preview: 'https://bootswatch.com/litera/',
    css: 'https://bootswatch.com/4/litera/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/litera/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/litera/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/litera/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/litera/_variables.scss',
    dark: false,
  },
  {
    name: 'Lumen',
    description: 'Light and shadow',
    thumbnail: 'https://bootswatch.com/lumen/thumbnail.png',
    preview: 'https://bootswatch.com/lumen/',
    css: 'https://bootswatch.com/4/lumen/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/lumen/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/lumen/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/lumen/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/lumen/_variables.scss',
    dark: false,
  },
  {
    name: 'Lux',
    description: 'A touch of class',
    thumbnail: 'https://bootswatch.com/lux/thumbnail.png',
    preview: 'https://bootswatch.com/lux/',
    css: 'https://bootswatch.com/4/lux/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/lux/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/lux/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/lux/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/lux/_variables.scss',
    dark: false,
  },
  {
    name: 'Materia',
    description: 'Material is the metaphor',
    thumbnail: 'https://bootswatch.com/materia/thumbnail.png',
    preview: 'https://bootswatch.com/materia/',
    css: 'https://bootswatch.com/4/materia/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/materia/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/materia/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/materia/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/materia/_variables.scss',
    dark: false,
  },
  {
    name: 'Minty',
    description: 'A fresh feel',
    thumbnail: 'https://bootswatch.com/minty/thumbnail.png',
    preview: 'https://bootswatch.com/minty/',
    css: 'https://bootswatch.com/4/minty/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/minty/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/minty/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/minty/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/minty/_variables.scss',
    dark: false,
  },
  {
    name: 'Pulse',
    description: 'A trace of purple',
    thumbnail: 'https://bootswatch.com/pulse/thumbnail.png',
    preview: 'https://bootswatch.com/pulse/',
    css: 'https://bootswatch.com/4/pulse/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/pulse/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/pulse/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/pulse/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/pulse/_variables.scss',
    dark: false,
  },
  {
    name: 'Sandstone',
    description: 'A touch of warmth',
    thumbnail: 'https://bootswatch.com/sandstone/thumbnail.png',
    preview: 'https://bootswatch.com/sandstone/',
    css: 'https://bootswatch.com/4/sandstone/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/sandstone/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/sandstone/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/sandstone/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/sandstone/_variables.scss',
    dark: false,
  },
  {
    name: 'Simplex',
    description: 'Mini and minimalist',
    thumbnail: 'https://bootswatch.com/simplex/thumbnail.png',
    preview: 'https://bootswatch.com/simplex/',
    css: 'https://bootswatch.com/4/simplex/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/simplex/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/simplex/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/simplex/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/simplex/_variables.scss',
    dark: false,
  },
  {
    name: 'Sketchy',
    description: 'A hand-drawn look for mockups and mirth',
    thumbnail: 'https://bootswatch.com/sketchy/thumbnail.png',
    preview: 'https://bootswatch.com/sketchy/',
    css: 'https://bootswatch.com/4/sketchy/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/sketchy/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/sketchy/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/sketchy/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/sketchy/_variables.scss',
    dark: false,
  },
  {
    name: 'Slate',
    description: 'Shades of gunmetal gray',
    thumbnail: 'https://bootswatch.com/slate/thumbnail.png',
    preview: 'https://bootswatch.com/slate/',
    css: 'https://bootswatch.com/4/slate/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/slate/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/slate/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/slate/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/slate/_variables.scss',
    dark: true,
  },
  {
    name: 'Solar',
    description: 'A spin on Solarized',
    thumbnail: 'https://bootswatch.com/solar/thumbnail.png',
    preview: 'https://bootswatch.com/solar/',
    css: 'https://bootswatch.com/4/solar/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/solar/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/solar/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/solar/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/solar/_variables.scss',
    dark: true,
  },
  {
    name: 'Spacelab',
    description: 'Silvery and sleek',
    thumbnail: 'https://bootswatch.com/spacelab/thumbnail.png',
    preview: 'https://bootswatch.com/spacelab/',
    css: 'https://bootswatch.com/4/spacelab/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/spacelab/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/spacelab/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/spacelab/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/spacelab/_variables.scss',
    dark: false,
  },
  {
    name: 'Superhero',
    description: 'The brave and the blue',
    thumbnail: 'https://bootswatch.com/superhero/thumbnail.png',
    preview: 'https://bootswatch.com/superhero/',
    css: 'https://bootswatch.com/4/superhero/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/superhero/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/superhero/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/superhero/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/superhero/_variables.scss',
    dark: true,
  },
  {
    name: 'United',
    description: 'Ubuntu orange and unique font',
    thumbnail: 'https://bootswatch.com/united/thumbnail.png',
    preview: 'https://bootswatch.com/united/',
    css: 'https://bootswatch.com/4/united/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/united/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/united/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/united/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/united/_variables.scss',
    dark: false,
  },
  {
    name: 'Yeti',
    description: 'A friendly foundation',
    thumbnail: 'https://bootswatch.com/yeti/thumbnail.png',
    preview: 'https://bootswatch.com/yeti/',
    css: 'https://bootswatch.com/4/yeti/bootstrap.css',
    cssMin: 'https://bootswatch.com/4/yeti/bootstrap.min.css',
    cssCdn: 'https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/yeti/bootstrap.min.css',
    scss: 'https://bootswatch.com/4/yeti/_bootswatch.scss',
    scssVariables: 'https://bootswatch.com/4/yeti/_variables.scss',
    dark: false,
  },
];
